### PR TITLE
SSL/TLS implementation 

### PR DESCRIPTION
**Pull request by grimmjo**

### CODE REVIEW

**Comment by grimmjo** [comment]
@graemerocher can you review this or authorize me to merge this PR? 
Did you change this behavior?

**Comment by graemerocher** [comment]
@grimmjo sorry about that, this repo shouldn't have been included in the new branch protection rules. Will get it sorted.

**Comment by graemerocher** [comment]
I have approved in the meantime

**Comment by graemerocher** [comment]
I disabled branch protection for this repo. Thanks

**Comment by grimmjo** [comment]
Thanks @graemerocher

**Pull request merged**
