### PR TITLE
Upgrade NATS Client to 2.11.0

### PR DESCRIPTION
**Pull request by marcosflobo**
NATS client (jnats) is released some days ago, and both 2.10.0 and 2.11.0 come with interesting features
- https://github.com/nats-io/nats.java/releases/tag/2.11.0

### CODE REVIEW

**Comment by ilopmar** [comment]
We can merge this and make a new release but we can't include this in Micronaut BOM until next minor version. That should be Micronaut 2.6 but that won't happen and we will include it in Micronaut 3.0.
We can't upgrade versions of the modules in Micronaut patch releases, so once it's released you need to manually set the new version.
I'll add this to my TODO list.

**Comment by marcosflobo** [comment]
@ilopmar so, you mean that this will upgrade will not come in an official micronaut-nats release until Micronaut BOM 3.0 is out, did I understood correctly?

**Comment by ilopmar** [comment]
@marcosflobo sorry, I should have explained this better. 

I can release a new minor version of micronaut-nats module (2.3.0) with this change, but the change won't be included in Micronaut 2.5.x BOM because we can't include modules minor versions in micronaut patch versions. 
Check this for more information: https://github.com/micronaut-projects/micronaut-core/wiki/Module-Upgrade-Strategy.


This means:
- If you create a new Micronaut 2.5.x version with the NATS module you will get the current version of the module (2.2.1) because that is the version in Micronaut 2.5.x BOM
- Once a I release a new minor version of the module (2.3.0) it will be included in Micronaut 3.0.x BOM
- If you want to use micronaut-nats 2.3.0 in Micronaut 2.5.x you can do it, but you need to set the version explictly.

Does this make sense?

**Comment by marcosflobo** [comment]
@ilopmar thanks for the further explanation, sorry if I was a bit slow there :) , it's clear to me now.

> If you want to use micronaut-nats 2.3.0 in Micronaut 2.5.x you can do it, but you need to set the version explictly.
That scenario would be ok to me

**Comment by ilopmar** [comment]
Upgraded in PR #152 and released in `2.3.0`. @marcosflobo you can now set manually the new version :-)

**Pull request closed without merging**
